### ISSUE TITLE
微信用户绑定报错

### ISSUE THREAD

**Issue by poguanzi** [sosyuki/wechat#1]
点击微信用户时报错

`Notice: Undefined index: user_bind_settings_form 在 drupal_retrieve_form() (行 807 在 /includes/form.inc).
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'user_bind_settings_form' not found or invalid function name 在 drupal_retrieve_form() (行 842 在 /includes/form.inc).`

**Comment by ankaiyuan** [comment]
fix 7.x-2.1
